### ISSUE TITLE
uuid1_clockseq()

### ISSUE THREAD

**Issue by nviennot** [zyro/elixir-uuid#10]
On the following snippet: https://github.com/zyro/elixir-uuid/blob/master/lib/uuid.ex#L440-L448
It seems that the whole thing is equivalent to `:crypto.rand_bytes(2)` (well, the first 14 bits) since the random generator is reseeded at every call, so there is no sequencing going on. Is this a problem?

**Comment by zyro** [comment]
From section 4.1.5. of [the RFC](http://www.ietf.org/rfc/rfc4122.txt):
> If the previous value of the clock sequence is known, it can just be incremented; otherwise it should be set to a random or high-quality pseudo-random value.

So a random clock sequence is OK. Alternatively `UUID.uuid1/3` takes a clock sequence and node values, so the application can choose to track the previous ones if this is needed.

**Comment by nviennot** [comment]
In that case, `uuid1_clockseq()` can be implemented with just a call to `rand_bytes(2)` ? Otherwise, the code seems a bit deceptive.
