### ISSUE TITLE
Hexdocs broken

### ISSUE THREAD

**Issue by Nicd** [zyro/elixir-uuid#14]
Docs on hex.pm for the latest version are broken: https://hex.pm/packages/uuid/1.1.2 links to http://hexdocs.pm/uuid/ which shows a "page not found" error. Docs for older versions like 1.1.1 work fine. Unsure if this is an error in hex.pm or your side.

**Comment by zyro** [comment]
Thanks for pointing that out, looks like an error in the `mix.exs` documentation metadata. I've fixed it and pushed a 1.1.3 release, the docs look OK now. Let me know if you still have issues.
