### ISSUE TITLE
Offer safe functions that return error tuples on failure instead of raising an exception

### ISSUE THREAD

**Issue by lpil** [zyro/elixir-uuid#15]
Hello!

It would be nice if functions returned `{:ok, data}` and `{:error, reason}` so we could handle failure through pattern matching, as is idomatic in Elixir. :)

Thanks,
Louis

**Comment by zyro** [comment]
Absolutely agreed, this has been on my wishlist for a while now.

I'm working on a wider refactor of most of the code, which will include functions that return tagged tuples. If there are other improvements you'd like to see, now is a good time to open more issues! :smile:

**Comment by lpil** [comment]
Thank you :D

**Comment by divmgl** [comment]
I'd like to assist if you need help with this task. Great work @zyro
