### ISSUE TITLE
New releases not available on hex.pm

### ISSUE THREAD

**Issue by thoughtarray** [zyro/elixir-uuid#46]
On GitHub, release v1.2.1 is available, but on hex.pm the latest is v1.1.8.

**Comment by nulian** [comment]
The library was renamed to elixir_uuid

**Comment by thoughtarray** [comment]
Okay, good to know. I see that mentioned in the README on GitHub. I think this should be featured prominently on hex.pm for the `uuid` package as well as the linked documentation.

**Comment by nacengineer** [comment]
@thoughtarray it's mostly legacy housekeeping but you should be able to close this issue :)
